### ISSUE TITLE
Where can it be downloaded?

### ISSUE THREAD

**Issue by probonopd** [davidcl/Scilab.AppDir#1]
Where can the AppImage be downloaded?

**Comment by davidcl** [comment]
Hi, I plan to use travis-ci deployements to ship something on GitHub releases ; in the meantime you could use this project as an helper to build your own binary.

**Comment by davidcl** [comment]
Available in the release section, see https://github.com/davidcl/Scilab.AppDir/releases and https://github.com/davidcl/Scilab.AppDir/releases/download/6.0.2-1/Scilab-x86_64.AppImage
